//TODO use yargs to parse restify add:env --database --name=name --password= pass ....
//TODO use yargs to parse restify add:env --jwt --name=name --password= pass ....
//TODO use yargs to parse restify add:env --mail --name=name --password= pass ....
